### ISSUE TITLE
PDF version of README.md?

### ISSUE THREAD

**Issue by ghost** [trimstray/nginx-admins-handbook#10]
This is really less of an issue and more of a recommendation / Question.
Would it be welcomed if I were to create a PDF version of this handbook, complete with working bookmarks that lead to each section so that it may be hosted and linked somewhere for those of us who prefer pdf versions of documentation?

I am unsure about the "standards" for linking pdf's vs actually adding them to a repository on github. I know .exe files are generally kept off of github (though I had them up for ease of access to a team...... smh)

**Comment by trimstray** [comment]
Hi @KonigKlack,

It's a great idea!

**Comment by ghost** [comment]
I'll get to it then!
How do you feel about including the PDF in the repo?

**Comment by trimstray** [comment]
Of course I'll join it :)

However, I would like the pdf version of this repo to be generated after each commit, it can be manually.

**Comment by ghost** [comment]
Sorry for the delay, I'm currently looking into ways I can automate this process so that it can be as simple as running a script after each commit

Edit: I tried it manually, I regret that dearly

**Comment by trimstray** [comment]
Hi @KonigKlack 

Cheer up, mate :) Maybe I can help you? Show what you have already done.

**Comment by trimstray** [comment]
I think it's too complicated.
