### ISSUE TITLE
Paragraph is unclear

### ISSUE THREAD

**Issue by harleypig** [trimstray/nginx-admins-handbook#11]
A paragraph in this [section](https://github.com/trimstray/nginx-admins-handbook#directives-blocks-and-contexts) is unclear:

> Directives are organised into groups known as blocks or contexts. Generally context is a block directive can have other directives inside braces. It appears to be organised in a tree-like structure, defined by sets of brackets - { and }.

Also, "generally" is generally followed by a comma.

Is this a valid interpretation of this sentence?

> Generally, context is a block directive **that** can have other directives inside braces.

**Comment by trimstray** [comment]
Thx!
