### ISSUE TITLE
New tool

### ISSUE THREAD

**Issue by therb1** [trimstray/nginx-admins-handbook#12]
Hello, thanks for your work.
Can you add our tool to your handbook?
```
A tool to build deb or rpm package of required Nginx version from the source code, with the ability to connect third-party modules.
Nginx parameters are set in the yaml configuration file.
```
https://github.com/TinkoffCreditSystems/Nginx-builder

**Comment by trimstray** [comment]
Hi @therb1 

Thanks! I'll add this but if you will translate README into English (or add next to it).

You can do it?

**Comment by therb1** [comment]
Hi @trimstray 

I translated the documentation like you asked.

**Comment by trimstray** [comment]
@therb1 :1st_place_medal:
