### ISSUE TITLE
Black high-res hardening checklist must be inverted in colors

### ISSUE THREAD

**Issue by korint** [trimstray/nginx-admins-handbook#2]
Well subj :) Not good for printing black pages. Wastes cartridge and environment.

**Comment by trimstray** [comment]
This repository contain editable [nginx-hardening-checklist.xcf](https://github.com/trimstray/nginx-quick-reference/blob/master/static/img/nginx-hardening-checklist.xcf) file.

I set the white background and fonts to black but the new file took over 3MB - I don't want the repository to be unnecessarily heavy.
